sudo: required

# Placeholder installs
before_install:
  - sudo apt-get install libao-dev
  - sudo apt-get install libcurl4-openssl-dev

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Placeholder install scripts
install:
  - pass

# Build steps
script:
  - make clean build
  - sudo make install

# Run examples
after_install:
  - cd ./examples
  - make
  - export LD_LIBRARY_PATH=/usr/local/lib/
  - ./mb_insert_test
  - ./mb_iterator_test
  - ./mb_longest_prefix_test
  - ./mb_lookup_test
  - ./mb_multi_proc_test
  - ./mb_remove_test
